<<<<<<< HEAD
title:              salvobertoncini
email:              info@salvobertoncini.com
description:        Blog Salvobertoncini
author:             Start Bootstrap
baseurl:            "/salvobertoncini.github.io"
url:                "www.salvobertoncini.com"

# Social Profiles
twitter_username:   salvobertoncini
github_username:    salvobertoncini
facebook_username:  
instagram_username:  
linkedin_username:  salvobertoncini

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
=======
theme: jekyll-theme-cayman
>>>>>>> 070eef16ea33f3bd8aa2639f5836b6390d38bc02
